apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: viola-back-prod-app # This value was modified by the initial-setup python script
  namespace: argocd
spec:
  destination:
    namespace: viola-prod # This value was modified by the initial-setup python script
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm/my-app/backend
    helm:
      valueFiles:
        - environments/values-prod.yaml
    repoURL: https://github.com/tomasferrarisenda/automate-all-the-things.git # This value was modified by the initial-setup python script
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
